#!/usr/bin/env bash
# File transfer SCP

if [ $# != 4 ]
then
    echo "USAGE: ./f_transfer_scp_toserver SSH_KEY_PATH LOCAL_FILE SSH_ALIAS FOLDER_ON_SERVER"
else
    scp -o StrictHostKeyChecking=no -i "$1" "$2" "$3":"$4"
fi

