#!/usr/bin/env bash
# File transfer rsync (without interruptions)

if [ $# != 2 ]
then
    echo "USAGE: ./file_transfer_scp LOCAL_FILE SSH_ALIAS"
else
    rsync --partial --progress --rsh=ssh "$1" "$2":"$1"
fi
